<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.dickinson.cs</groupId>
        <artifactId>taskflow-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>taskflow-peer</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.dickinson.cs</groupId>
            <artifactId>taskflow-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.dickinson.cs</groupId>
            <artifactId>taskflow-plugin-conversion-client</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.dickinson.cs</groupId>
            <artifactId>taskflow-plugin-conversion-peer</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.dickinson.cs</groupId>
            <artifactId>taskflow-plugin-text-client</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.dickinson.cs</groupId>
            <artifactId>taskflow-plugin-text-peer</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.dickinson.cs</groupId>
            <artifactId>taskflow-transport-rabbitmq</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <mainClass>peer.PeerNode</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <id>make-shaded-runtime-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>jar-with-dependencies</shadedClassifierName>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>peer.PeerNode</mainClass>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
