<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.dickinson.cs</groupId>
        <artifactId>taskflow-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>taskflow-gui</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.dickinson.cs</groupId>
            <artifactId>taskflow-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>com.dickinson.cs</groupId>
            <artifactId>taskflow-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.dickinson.cs</groupId>
            <artifactId>taskflow-persistence-sqlite</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>combined-runtime</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.dickinson.cs</groupId>
                    <artifactId>taskflow-plugin-conversion-client</artifactId>
                    <scope>runtime</scope>
                </dependency>
                <dependency>
                    <groupId>com.dickinson.cs</groupId>
                    <artifactId>taskflow-plugin-conversion-peer</artifactId>
                    <scope>runtime</scope>
                </dependency>
                <dependency>
                    <groupId>com.dickinson.cs</groupId>
                    <artifactId>taskflow-plugin-text-client</artifactId>
                    <scope>runtime</scope>
                </dependency>
                <dependency>
                    <groupId>com.dickinson.cs</groupId>
                    <artifactId>taskflow-plugin-text-peer</artifactId>
                    <scope>runtime</scope>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>submitter-runtime</id>
            <dependencies>
                <dependency>
                    <groupId>com.dickinson.cs</groupId>
                    <artifactId>taskflow-plugin-conversion-client</artifactId>
                    <scope>runtime</scope>
                </dependency>
                <dependency>
                    <groupId>com.dickinson.cs</groupId>
                    <artifactId>taskflow-plugin-text-client</artifactId>
                    <scope>runtime</scope>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>executor-runtime</id>
            <dependencies>
                <dependency>
                    <groupId>com.dickinson.cs</groupId>
                    <artifactId>taskflow-plugin-conversion-peer</artifactId>
                    <scope>runtime</scope>
                </dependency>
                <dependency>
                    <groupId>com.dickinson.cs</groupId>
                    <artifactId>taskflow-plugin-text-peer</artifactId>
                    <scope>runtime</scope>
                </dependency>
            </dependencies>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <configuration>
                    <mainClass>gui.PeerApp</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
